groups:
  - name: pushgateway
    rules:
      - alert: SamplePythonClient
        expr: time() - push_time_seconds{exported_job="sample_job"} > 60
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "sample_job down"
          description: "sample_job down"
          text: "めっちゃ適当なテキスト"

  - name: node-exporter
    rules:
      - alert: instance_down_frontend
        expr: up{team="frontend"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."
          text: "node-exporter instance down at frontend"

      - alert: instance_down_backend
        expr: up{team="backend"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."
          text: "node-exporter instance down at frontend"

  - name: cadvisor
    rules:
      - record: cadvisor_job:container_last_seen_by_project:container_monitoring
        expr: sum without(container_label_com_docker_compose_config_hash,id) (container_last_seen{container_label_com_docker_compose_project="container_monitoring"})
      - alert: instance_down_container_monitoring
        expr: time() - cadvisor_job:container_last_seen_by_project:container_monitoring > 60
        for: 2m
        labels:
          severity: critical
        annotations:
          text: "down container {{ $labels.name }}"

      - record: cadvisor_job:container_last_seen_by_project:resin_visualizer
        expr: sum without(container_label_com_docker_compose_config_hash,id) (container_last_seen{container_label_com_docker_compose_project="resin_visualizer"})
      - alert: instance_down_resin_visualizer
        expr: time() - cadvisor_job:container_last_seen_by_project:resin_visualizer > 60
        for: 2m
        labels:
          severity: critical
        annotations:
          text: "down container {{ $labels.name }}"

      - record: cadvisor_job:container_last_seen_by_project:trend_monitoring
        expr: sum without(container_label_com_docker_compose_config_hash,id) (container_last_seen{container_label_com_docker_compose_project="trend_monitoring"})
      - alert: instance_down_trend_monitoring
        expr: time() - cadvisor_job:container_last_seen_by_project:trend_monitoring > 60
        for: 2m
        labels:
          severity: critical
        annotations:
          text: "down container {{ $labels.name }}"
